# Autogenerated wrapper script for p7zip_jll for x86_64-w64-mingw32
export p7zip

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("p7zip")
JLLWrappers.@declare_executable_product(p7zip)
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_executable_product(
        p7zip,
        "bin\\7z.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
